# netlify.toml

[build]
  # If your site builds to a folder (e.g., "dist"), change this to that folder.
  publish = "."
  # Uncomment if you have a build command (e.g., npm run build)
  # command = "npm run build"

  [build.processing]
    # Make sure post-processing runs so Netlify Forms gets picked up
    skip_processing = false

  [build.processing.css]
    bundle = true
    minify = true

  [build.processing.js]
    bundle = false   # set true if you want Netlify to bundle plain JS
    minify = true

  [build.processing.html]
    pretty_urls = true
    minify = true

  [build.processing.images]
    compress = true

  # Explicitly ensure Forms are processed (belt & suspenders)
  [build.processing.forms]
    enable = true

# ---------- Redirects ----------
# If you ever need a clean URL for /dashboard (no .html), this is already
# handled by Pretty URLs. But you can force it with the rule below:
# [[redirects]]
#   from = "/dashboard"
#   to = "/dashboard.html"
#   status = 200
#   force = true

# If you later turn this into a SPA, uncomment this to serve index.html for all routes:
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# ---------- Headers ----------
# Long-term caching for static assets (tweak paths as needed)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Reasonable caching for JSON dataset (so updates propagate faster)
[[headers]]
  for = "/assets/us_institutions_by_state_2023.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Security headers (adjust CSP to your needs if you add external scripts)
[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    # A relaxed CSP that allows Google Fonts and Netlify assets.
    # Tighten this as you lock down sources.
    Content-Security-Policy = "default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; script-src 'self'; connect-src 'self' https://cdn.jsdelivr.net https://raw.githubusercontent.com; frame-ancestors 'self'; base-uri 'self'; form-action 'self'"

# ---------- Forms (optional explicit declaration) ----------
# Netlify does not require this block for forms to work when the HTML includes:
#   data-netlify="true" and <input type="hidden" name="form-name" value="contact-admin">
# Leaving this here for clarity; it won’t hurt.
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  # Remove if you don't want Lighthouse reports on deploy

# You can also add functions if you later want to send email via an API
# [functions]
#   directory = "netlify/functions"
