[build]
  # Serve everything in the /public folder
  publish = "public"
  # No build step — it's a static site
  command = ""

[build.environment]
  NODE_VERSION = "18"

# Redirect root to /dashboard
[[redirects]]
  from = "/"
  to   = "/dashboard"
  status = 200
  force = true

# Optional: handle trailing slashes and SPA-style routes
[[redirects]]
  from = "/*"
  to = "/dashboard"
  status = 200
[build]
  publish = "public"
  command = ""

# Send "/" to "/dashboard"
[[redirects]]
  from = "/"
  to   = "/dashboard"
  status = 200
