[build]
  publish = "public"
  command = ""

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/"
  to   = "/dashboard"
  status = 200

[[redirects]]
  from = "/dashboard"
  to   = "/dashboard.html"
  status = 200

# API routes for backend functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
