# Netlify deployment configuration for StellarRec Frontend

[build]
  publish = "."
  command = "echo 'Building StellarRec Frontend...'"

# Redirect rules handled by _redirects file

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://fonts.googleapis.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; media-src 'self' data: blob: https://player.vimeo.com https://vod-progressive.akamaized.net; connect-src 'self' https://api.stellarrec.com wss://api.stellarrec.com;"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "video/mp4"

[[headers]]
  for = "*.webm"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "video/webm"

[[headers]]
  for = "*.gif"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/gif"

# Form handling (for contact forms, etc.)
# [[forms]]
#   name = "contact"
#   action = "/contact-success"
  
# Edge functions (if needed for advanced features)
# [[edge_functions]]
#   function = "auth-check"
#   path = "/dashboard/*"

# Environment-specific settings
[context.production.environment]
  API_URL = "https://api.stellarrec.com"
  ENVIRONMENT = "production"