# netlify.toml (put at the repo root)

[build]
  publish = "public"
  command = ""

# Redirect the site root to /dashboard
[[redirects]]
  from = "/"
  to   = "/dashboard"
  status = 200

# Make /dashboard resolve to /dashboard.html (handy for static sites)
[[redirects]]
  from = "/dashboard"
  to   = "/dashboard.html"
  status = 200
