#!/usr/bin/env node

/**
 * Simple setup script for StellarRec backend configuration
 * This helps you configure the backend without needing paid environment variables
 */

import fs from 'fs';
import crypto from 'crypto';
import readline from 'readline';

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function question(prompt) {
  return new Promise((resolve) => {
    rl.question(prompt, resolve);
  });
}

async function setup() {
  console.log('🚀 StellarRec Backend Setup');
  console.log('============================\n');

  console.log('This will help you configure your backend for free deployment.\n');

  // Get Resend API key
  console.log('📧 Email Service Setup:');
  console.log('1. Go to https://resend.com');
  console.log('2. Sign up (free - 100 emails/day)');
  console.log('3. Create an API key\n');

  const apiKey = await question('Enter your Resend API key (or press Enter to skip): ');

  // Generate random secret
  const randomSecret = crypto.randomBytes(32).toString('hex');
  console.log(`\n🔐 Generated secure signing secret: ${randomSecret.substring(0, 20)}...\n`);

  // Email from address
  const emailFrom = await question('Enter sender email (default: StellarRec <no-reply@stellarrec.com>): ') || 'StellarRec <no-reply@stellarrec.com>';

  // Create config
  const configContent = `// Configuration file for StellarRec backend
// Generated by setup script on ${new Date().toISOString()}

export const config = {
  // Resend API key for sending emails
  RESEND_API_KEY: '${apiKey || 'your_resend_api_key_here'}',
  
  // Email settings
  EMAIL_FROM: '${emailFrom}',
  
  // Frontend URL
  FRONTEND_BASE: 'https://stellarrec.netlify.app/dashboard',
  
  // Security secret for signing links
  SIGNING_SECRET: '${randomSecret}',
  
  // Development mode
  DEV_MODE: ${!apiKey}
};

// To update configuration:
// 1. Edit the values above
// 2. Commit and push changes to deploy
`;

  // Write config file
  fs.writeFileSync('netlify/functions/config.js', configContent);

  console.log('✅ Configuration saved to netlify/functions/config.js');
  
  if (!apiKey) {
    console.log('\n⚠️  No API key provided - running in development mode');
    console.log('   Emails will be logged to console instead of sent');
    console.log('   Add your Resend API key later to enable real emails');
  } else {
    console.log('\n🎉 Email service configured and ready!');
  }

  console.log('\n📝 Next steps:');
  console.log('1. Commit and push changes: git add . && git commit -m "Configure backend" && git push');
  console.log('2. Your backend will be available at: https://stellarrec.netlify.app/.netlify/functions/recommendations');
  console.log('3. Test the health check: https://stellarrec.netlify.app/.netlify/functions/health');

  rl.close();
}

setup().catch(console.error);