version: '3.8'

services:
  # Database Services
  postgres:
    image: postgres:15-alpine
    container_name: stellarrec-postgres
    environment:
      POSTGRES_DB: stellarrec_dev
      POSTGRES_USER: stellarrec
      POSTGRES_PASSWORD: stellarrec_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - stellarrec-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: stellarrec-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - stellarrec-network

  # Elasticsearch for Search
  elasticsearch:
    image: elasticsearch:8.11.0
    container_name: stellarrec-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - stellarrec-network

  # API Gateway
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    container_name: stellarrec-api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=stellarrec_jwt_secret_dev
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - user-service
      - ai-service
      - application-service
    networks:
      - stellarrec-network

  # User Management Service
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: stellarrec-user-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DATABASE_URL=postgresql://stellarrec:stellarrec_dev_password@postgres:5432/stellarrec_dev
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=stellarrec_jwt_secret_dev
    depends_on:
      - postgres
      - redis
    networks:
      - stellarrec-network

  # AI/ML Service
  ai-service:
    build:
      context: ./services/ai-service
      dockerfile: Dockerfile
    container_name: stellarrec-ai-service
    ports:
      - "8002:8002"
    environment:
      - ENVIRONMENT=development
      - PORT=8002
      - DATABASE_URL=postgresql://stellarrec:stellarrec_dev_password@postgres:5432/stellarrec_dev
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SECRET_KEY=stellarrec_ai_secret_dev
      - DEBUG=true
    volumes:
      - ./services/ai-service:/app
      - ai_models:/app/models
    depends_on:
      - postgres
      - redis
      - elasticsearch
    networks:
      - stellarrec-network
    restart: unless-stopped

  # Application Management Service
  application-service:
    build:
      context: ./services/application-service
      dockerfile: Dockerfile
    container_name: stellarrec-application-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DATABASE_URL=postgresql://stellarrec:stellarrec_dev_password@postgres:5432/stellarrec_dev
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - stellarrec-network

  # File Management Service
  file-management:
    build:
      context: ./services/file-management
      dockerfile: Dockerfile
    container_name: stellarrec-file-management
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=development
      - PORT=3009
      - DATABASE_URL=postgresql://stellarrec:stellarrec_dev_password@postgres:5432/stellarrec_dev
      - JWT_SECRET=stellarrec_jwt_secret_dev
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-minioadmin}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-minioadmin}
      - AWS_REGION=us-east-1
      - S3_BUCKET=stellarrec-files
      - S3_ENDPOINT=http://minio:9000
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
    depends_on:
      - postgres
      - minio
    networks:
      - stellarrec-network

  # Document Processing Service
  document-processing:
    build:
      context: ./services/document-processing
      dockerfile: Dockerfile
    container_name: stellarrec-document-processing
    ports:
      - "3010:3010"
    environment:
      - NODE_ENV=development
      - PORT=3010
      - DATABASE_URL=postgresql://stellarrec:stellarrec_dev_password@postgres:5432/stellarrec_dev
      - JWT_SECRET=stellarrec_jwt_secret_dev
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_INDEX=stellarrec-documents
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost:3001
      - MAX_FILE_SIZE=104857600
      - TEMP_DIR=/tmp
      - DEFAULT_OCR_LANGUAGE=eng
    depends_on:
      - postgres
      - elasticsearch
    networks:
      - stellarrec-network

  # MinIO for S3-compatible storage
  minio:
    image: minio/minio:latest
    container_name: stellarrec-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - stellarrec-network

volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:
  ai_models:
  minio_data:

networks:
  stellarrec-network:
    driver: bridge